apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx_server 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx_app
  template:
    metadata:
      labels:
        app: nginx_app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:   #Recursos "mínimos"
            memory: "100Mi"
            cpu: "100m"
          limits:     #Limite de recursos
            memory: "200Mi"
            cpu: "300m"
