apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2021-10-31T23:56:51Z"
  name: stress-test
  namespace: default
  resourceVersion: "48765"
  uid: de559d12-8030-4149-9e73-a20bb9c5237a
spec:
  maxReplicas: 10                         # Máximo de réplicas que serão criadas pelo autoscaler
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-test
  targetCPUUtilizationPercentage: 90      # Cria mais pods se a utilização de cpu superar 90%
status:
  currentReplicas: 0
  desiredReplicas: 0
