apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stress-test
  name: stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stress-test
    spec:
      containers:
      - image: polinux/stress
        name: stress
        resources: {}
        command: ["/bin/sh", "-c"]
        args: 
          - "stress -c 1 --vm 1 --vm-bytes 100M"
status: {}
