app:
  message: "Mensagem show de bola!"
  replicas: 2
  resources:
    requests:
      cpu: "200m"
      memory: "100Mi"
    limits:
      cpu: "500m"
      memory: "200Mi"
service:
  type: ClusterIP
  port: 9999