apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-app
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - image: maurifc/hello-env
        name: helm-teste-app-container
        ports:
          - containerPort: 8888
        resources: 
          requests:
            cpu: {{ .Values.app.resources.requests.cpu }}
            memory: {{ .Values.app.resources.requests.memory }}
          limits:
            cpu: {{ .Values.app.resources.limits.cpu }}
            memory: {{ .Values.app.resources.limits.memory }}
        env:
          - name: MSG
            value: {{ .Values.app.message }}