apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"goapp"},"name":"mygoapp","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"goapp"}},"template":{"metadata":{"labels":{"app":"goapp"}},"spec":{"containers":[{"image":"maurifc/myhello","name":"hello","ports":[{"containerPort":8888}]}]}}}}
    creationTimestamp: "2021-10-31T14:23:54Z"
    generation: 1
    labels:
      app: goapp
    name: mygoapp
    namespace: default
    resourceVersion: "38930"
    uid: 9743f0d7-d714-47ce-948d-07c989ae26b4
  spec:
    progressDeadlineSeconds: 600
    replicas: 10
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: goapp
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: goapp
      spec:
        containers:
        - image: maurifc/myhello
          imagePullPolicy: Always
          name: hello
          ports:
          - containerPort: 8888
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2021-10-31T14:24:01Z"
      lastUpdateTime: "2021-10-31T14:24:01Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-10-31T14:23:54Z"
      lastUpdateTime: "2021-10-31T14:24:01Z"
      message: ReplicaSet "mygoapp-78c7d8f8b8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
