apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"www","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8888}],"selector":{"app":"goapp"}}}
  creationTimestamp: "2021-10-31T14:22:14Z"
  name: www
  namespace: default
  resourceVersion: "38625"
  uid: 9edbc766-29e4-4c19-a419-6776234bcdbd
spec:
  clusterIP: 10.101.211.14
  clusterIPs:
  - 10.101.211.14
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: goapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
