apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygoapp
  labels:
    app: goapp 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: hello
        image: maurifc/myhello
        ports:
        - containerPort: 8888