apiVersion: v1
kind: LimitRange
metadata:
  name: demo-limitrange
spec:
  limits:
  - default:  #Limite máximo de uso
      cpu: "500m"
      memory: "256Mi"
    defaultRequest: #Recursos mínimos solicitados
      cpu: "200m"
      memory: "128Mi"
    type: Container
