# Fazer encaminhamento de porta para acessar o service:
# kubectl port-forward service/www 8080:80
# Acessar com localhost:8080
apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888