apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloenv
  name: helloenv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloenv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloenv
    spec:
      containers:
      - image: maurifc/hello-env
        name: hello-env
        resources: {}
        env:
        - name: MSG
          value: "Teste de msg"
        securityContext:
          runAsUser: 1000                   #Troca usuário que rodará o container
          runAsNonRoot: true                #Só inicia o container se ele não requerer root
          readOnlyRootFilesystem: true      #Habilita readonly no sistema de arquivos do container
          allowPrivilegeEscalation: false   #Evita escalonamento de privilégios caso o container invadido possua algum executável com setuid habilitado
          capabilities:                     
            drop: ["all"]
            add: ["NET_BIND_SERVICE"]       #Desabilita todas capabilities do processo e habilta somente a permissão para fazer um bind