apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: catfile
  name: catfile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catfile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catfile
    spec:
      containers:
      - image: maurifc/catfile
        name: catfile
        resources: {}
        volumeMounts:
          - mountPath: /app
            name: text-file-volume
            readOnly: true
      volumes:
        - name: text-file-volume
          configMap:
            name: app-configmap
            items:
            - key: file
              path: textfile.txt
