apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: catfile
  name: catfile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catfile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catfile
    spec:
      containers:
      - image: maurifc/catfile
        name: catfile
        resources: {}
        volumeMounts:                   # montamos um volume na pasta /app
          - mountPath: /app
            name: text-file-volume      # nome do volume a ser montado (deve ser igual ao da linha 29)
            readOnly: true
      volumes:                          # criamos um volume
        - name: text-file-volume        # nome do volume
          configMap:
            name: app-configmap         # nome do config map que contém os dados do volume
            items:
            - key: file                 # nome do bloco de dados do configmap que será copiado para o volume
              path: textfile.txt        # nome do arquivo final dentro do container
