apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appsecret
  name: appsecret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsecret
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appsecret
    spec:
      containers:
      - image: maurifc/asecret
        name: asecret
        env:
          - name: MSG                 # Variável de ambiente MSG é criada como se fosse uma env normal
            valueFrom:
              secretKeyRef:           # Porém informamos que iremos buscar o valor a partir do secret criado previamente
                name: app-secret      # Nome do secret
                key: message          # Nome da chave presente no secret
status: {}
